---
name: CI

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 8 1 *'

jobs:
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
    with:
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
  integration:
    uses: ansible-network/github_actions/.github/workflows/integration.yml@main
  ansible-lint:
    uses: ansible-network/github_actions/.github/workflows/ansible-lint.yml@main
  all_green:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - sanity
      - integration
      - ansible-lint
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.sanity.result }}',
          '${{ needs.integration.result }}',
          '${{ needs.ansible-lint.result }}',
          ])"
